/**
 * tickets.js — client-facing support ticket submission
 * POST /api/tickets  (multipart/form-data)
 * GET  /api/tickets/:id/attachment
 *
 * Attachments stored on cPanel disk at UPLOAD_DIR (default: ~/musharaka-uploads)
 */
const express  = require('express')
const router   = express.Router()
const multer   = require('multer')
const fs       = require('fs')
const path     = require('path')
const { randomUUID } = require('crypto')
const { pool, selectOne, insertOne } = require('../db/query')
const { authMiddleware }   = require('../middleware/auth')
const { tenantMiddleware } = require('../middleware/tenantMiddleware')
const { standardLimiter }  = require('../middleware/rateLimiter')

// ── Upload directory ──────────────────────────────────────────────────────────
const UPLOAD_DIR = process.env.UPLOAD_DIR ||
  path.join(process.env.HOME || process.env.USERPROFILE || '/tmp', 'musharaka-uploads')

try { fs.mkdirSync(UPLOAD_DIR, { recursive: true }) } catch { /* ignore */ }

// ── File upload config ───────────────────────────────────────────────────────
const ALLOWED_MIMES = ['image/png', 'image/jpeg', 'application/pdf']
const ALLOWED_EXTS  = ['.png', '.jpg', '.jpeg', '.pdf']

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 }, // 5 MB
  fileFilter: (_req, file, cb) => {
    const parts = file.originalname.split('.')
    if (parts.length < 2) {
      return cb(new multer.MulterError('LIMIT_UNEXPECTED_FILE', 'نوع الملف غير مدعوم'))
    }
    const ext = '.' + parts.pop().toLowerCase()
    if (ALLOWED_MIMES.includes(file.mimetype) && ALLOWED_EXTS.includes(ext)) {
      cb(null, true)
    } else {
      cb(new multer.MulterError('LIMIT_UNEXPECTED_FILE', 'يُسمح فقط بملفات PNG و JPG و PDF'))
    }
  },
})

function handleMulterError(err, req, res, next) {
  if (err instanceof multer.MulterError) {
    if (err.code === 'LIMIT_FILE_SIZE') return res.status(422).json({ error: 'الملف كبير جداً (الحد الأقصى 5 ميجابايت)' })
    return res.status(422).json({ error: err.field || 'خطأ في رفع الملف' })
  }
  next(err)
}

// ── POST /api/tickets ────────────────────────────────────────────────────────
router.post(
  '/',
  standardLimiter,
  authMiddleware,
  tenantMiddleware,
  upload.single('file'),
  handleMulterError,
  async (req, res, next) => {
    try {
      const { submitter_name, submitter_email, title, category, description, steps } = req.body

      if (!submitter_name)  return res.status(422).json({ error: 'الاسم مطلوب' })
      if (!submitter_email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(submitter_email))
        return res.status(422).json({ error: 'البريد الإلكتروني غير صحيح' })
      if (!title)           return res.status(422).json({ error: 'عنوان المشكلة مطلوب' })
      const ALLOWED_CATEGORIES = [
        'مبيعات', 'فروع', 'مستخدمون', 'ترخيص', 'تقني', 'أخرى',
        'integration', 'license', 'technical', 'reporting',
      ]
      if (!category || !ALLOWED_CATEGORIES.includes(category))
        return res.status(422).json({ error: 'يرجى اختيار تصنيف صحيح' })
      if (!description)     return res.status(422).json({ error: 'وصف المشكلة مطلوب' })

      const tenantId = req.tenantId

      // Fetch tenant name for denormalization
      const tenant = await selectOne('tenants', { id: tenantId })

      // Save attachment to disk (if provided)
      let attachment_url  = null
      let attachment_name = null

      if (req.file) {
        const ext      = req.file.originalname.split('.').pop().toLowerCase()
        const fileId   = randomUUID()
        const tenantDir = path.join(UPLOAD_DIR, tenantId)
        const filePath = path.join(tenantDir, `${fileId}.${ext}`)

        try {
          fs.mkdirSync(tenantDir, { recursive: true })
          fs.writeFileSync(filePath, req.file.buffer)
        } catch (writeErr) {
          console.error('[tickets] disk write error:', writeErr)
          return res.status(500).json({ error: 'فشل رفع الملف. يرجى المحاولة مجدداً.' })
        }

        // Store relative path; download goes through auth-gated endpoint
        attachment_url  = `${tenantId}/${fileId}.${ext}`
        attachment_name = req.file.originalname
      }

      // Insert ticket (ticket_number auto-generated by DB sequence)
      const ticket = await insertOne(
        'support_tickets',
        {
          tenant_id:       tenantId,
          tenant_name:     tenant?.name || '',
          submitter_name,
          submitter_email,
          title,
          category,
          description,
          steps:           steps || null,
          attachment_url,
          attachment_name,
        },
        'id, ticket_number'
      )

      res.status(201).json({ id: ticket.id, ticket_number: ticket.ticket_number })
    } catch (err) { next(err) }
  }
)

// ── GET /api/tickets/:id/attachment ──────────────────────────────────────────
router.get(
  '/:id/attachment',
  standardLimiter,
  authMiddleware,
  tenantMiddleware,
  async (req, res, next) => {
    try {
      const ticket = await selectOne('support_tickets', { id: req.params.id })
      if (!ticket) return res.status(404).json({ error: 'التذكرة غير موجودة' })

      // Tenant isolation: own tenant OR super-admin
      if (!req.isSuperAdmin && ticket.tenant_id !== req.tenantId) {
        return res.status(403).json({ error: 'غير مصرح' })
      }
      if (!ticket.attachment_url) return res.status(404).json({ error: 'لا يوجد مرفق' })

      // Path safety: reject any path traversal attempts
      const rel = ticket.attachment_url.replace(/^\/+/, '')
      if (rel.includes('..')) return res.status(400).json({ error: 'مسار غير صالح' })

      const filePath = path.join(UPLOAD_DIR, rel)
      if (!filePath.startsWith(path.resolve(UPLOAD_DIR))) {
        return res.status(400).json({ error: 'مسار غير صالح' })
      }
      if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'الملف غير موجود' })

      res.download(filePath, ticket.attachment_name || 'attachment')
    } catch (err) { next(err) }
  }
)

module.exports = router
