/**
 * tickets.js — client-facing support ticket submission
 * POST /api/tickets  (multipart/form-data)
 */
const express  = require('express')
const router   = express.Router()
const multer   = require('multer')
const { randomUUID } = require('crypto')
const { supabase }        = require('../config/supabase')
const { authMiddleware }  = require('../middleware/auth')
const { tenantMiddleware } = require('../middleware/tenantMiddleware')
const { standardLimiter } = require('../middleware/rateLimiter')

// ── File upload config ───────────────────────────────────────────────────────
const ALLOWED_MIMES = ['image/png', 'image/jpeg', 'application/pdf']
const ALLOWED_EXTS  = ['.png', '.jpg', '.jpeg', '.pdf']

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 }, // 5 MB
  fileFilter: (_req, file, cb) => {
    const parts = file.originalname.split('.')
    if (parts.length < 2) {
      return cb(new multer.MulterError('LIMIT_UNEXPECTED_FILE', 'نوع الملف غير مدعوم'))
    }
    const ext = '.' + parts.pop().toLowerCase()
    if (ALLOWED_MIMES.includes(file.mimetype) && ALLOWED_EXTS.includes(ext)) {
      cb(null, true)
    } else {
      cb(new multer.MulterError('LIMIT_UNEXPECTED_FILE', 'يُسمح فقط بملفات PNG و JPG و PDF'))
    }
  },
})

function handleMulterError(err, req, res, next) {
  if (err instanceof multer.MulterError) {
    if (err.code === 'LIMIT_FILE_SIZE') return res.status(422).json({ error: 'الملف كبير جداً (الحد الأقصى 5 ميجابايت)' })
    return res.status(422).json({ error: err.field || 'خطأ في رفع الملف' })
  }
  next(err)
}

// ── POST /api/tickets ────────────────────────────────────────────────────────
router.post(
  '/',
  standardLimiter,
  authMiddleware,
  tenantMiddleware,
  upload.single('file'),
  handleMulterError,
  async (req, res, next) => {
    try {
      const { submitter_name, submitter_email, title, category, description, steps } = req.body

      if (!submitter_name)  return res.status(422).json({ error: 'الاسم مطلوب' })
      if (!submitter_email) return res.status(422).json({ error: 'البريد الإلكتروني مطلوب' })
      if (!title)           return res.status(422).json({ error: 'عنوان المشكلة مطلوب' })
      if (!category || !['integration', 'license', 'technical', 'reporting'].includes(category))
        return res.status(422).json({ error: 'يرجى اختيار تصنيف صحيح' })
      if (!description)     return res.status(422).json({ error: 'وصف المشكلة مطلوب' })

      const tenantId = req.tenantId

      // Fetch tenant name for denormalization
      const { data: tenant } = await supabase
        .from('tenants')
        .select('name')
        .eq('id', tenantId)
        .single()

      // Upload attachment to Supabase Storage (if provided)
      let attachment_url  = null
      let attachment_name = null

      if (req.file) {
        const ext      = req.file.originalname.split('.').pop().toLowerCase()
        const filePath = `${tenantId}/${randomUUID()}.${ext}`

        const { error: uploadErr } = await supabase.storage
          .from('ticket-attachments')
          .upload(filePath, req.file.buffer, {
            contentType: req.file.mimetype,
            upsert: false,
          })

        if (uploadErr) {
          console.error('[tickets] storage upload error:', uploadErr)
          return res.status(500).json({ error: 'فشل رفع الملف. يرجى المحاولة مجدداً.' })
        }

        const { data: urlData } = supabase.storage
          .from('ticket-attachments')
          .getPublicUrl(filePath)

        attachment_url  = urlData.publicUrl
        attachment_name = req.file.originalname
      }

      // Insert ticket (ticket_number auto-generated by DB sequence)
      const { data: ticket, error: insertErr } = await supabase
        .from('support_tickets')
        .insert({
          tenant_id:       tenantId,
          tenant_name:     tenant?.name || '',
          submitter_name,
          submitter_email,
          title,
          category,
          description,
          steps:           steps || null,
          attachment_url,
          attachment_name,
        })
        .select('id, ticket_number')
        .single()

      if (insertErr) throw insertErr

      res.status(201).json({ id: ticket.id, ticket_number: ticket.ticket_number })
    } catch (err) { next(err) }
  }
)

module.exports = router
