name: Build React App
on:
  push:
    branches: [phase-2/ui-improvements-and-deployment]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build client
        working-directory: musharaka/client
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: Commit dist
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add musharaka/client/dist -f
          git commit -m "chore: add built dist folder"
          git push
